# coding: utf-8

# flake8: noqa
"""
    AutoMATES Common Abstract Syntax Tree (CAST) v1

    This document outlines the structure of the CAST that will be used as a generic representation of the semantics of a program written in any language. This will be used when creating functions networks from programs using the University of Arizonas program analysis pipeline.    Generating Python Class Structure   TODO look into https://pypi.org/project/swagger-to/    Generating POJOs TODO look into https://stackoverflow.com/questions/33354557/how-to-generate-java-client-code-for-swagger-rest-api-documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from automates.program_analysis.CAST2GrFN.model.cast.assignment import Assignment
from automates.program_analysis.CAST2GrFN.model.cast.ast_node import AstNode
from automates.program_analysis.CAST2GrFN.model.cast.attribute import Attribute
from automates.program_analysis.CAST2GrFN.model.cast.binary_op import BinaryOp
from automates.program_analysis.CAST2GrFN.model.cast.binary_operator import (
    BinaryOperator,
)
from automates.program_analysis.CAST2GrFN.model.cast.boolean import Boolean
from automates.program_analysis.CAST2GrFN.model.cast.call import Call
from automates.program_analysis.CAST2GrFN.model.cast.class_def import ClassDef
from automates.program_analysis.CAST2GrFN.model.cast.dict import Dict
from automates.program_analysis.CAST2GrFN.model.cast.expr import Expr
from automates.program_analysis.CAST2GrFN.model.cast.function_def import FunctionDef
from automates.program_analysis.CAST2GrFN.model.cast.list import List
from automates.program_analysis.CAST2GrFN.model.cast.loop import Loop
from automates.program_analysis.CAST2GrFN.model.cast.model_break import ModelBreak
from automates.program_analysis.CAST2GrFN.model.cast.model_continue import ModelContinue
from automates.program_analysis.CAST2GrFN.model.cast.model_if import ModelIf
from automates.program_analysis.CAST2GrFN.model.cast.model_return import ModelReturn
from automates.program_analysis.CAST2GrFN.model.cast.module import Module
from automates.program_analysis.CAST2GrFN.model.cast.name import Name
from automates.program_analysis.CAST2GrFN.model.cast.number import Number
from automates.program_analysis.CAST2GrFN.model.cast.set import Set
from automates.program_analysis.CAST2GrFN.model.cast.source_ref import SourceRef
from automates.program_analysis.CAST2GrFN.model.cast.string import String
from automates.program_analysis.CAST2GrFN.model.cast.source_ref import SourceRef
from automates.program_analysis.CAST2GrFN.model.cast.subscript import Subscript
from automates.program_analysis.CAST2GrFN.model.cast.tuple import Tuple
from automates.program_analysis.CAST2GrFN.model.cast.unary_op import UnaryOp
from automates.program_analysis.CAST2GrFN.model.cast.unary_operator import UnaryOperator
from automates.program_analysis.CAST2GrFN.model.cast.var import Var
from automates.program_analysis.CAST2GrFN.model.cast.var_type import VarType
