# !bin/bash



#PART 1: Requests resources to run your job.
# --------------------------------------------------------------
### Set the job name (needed for job lookup)
#PBS -N pdflatex_tester
### Specify the PI group for this job (always claytonm)
#PBS -W group_list=claytonm
### Set the queue for your job (options: windfall, standard, high_priority, debug -- only on Ocelote)
#PBS -q standard
### Set the number of nodes, cores and memory that will be used for this job
### pcmem is optional as it defaults to 6gb per core. Note: mem=ncpus x pcmem
#PBS -l select=25:ncpus=20:mem=80gb:pcmem=4gb
### Specify "wallclock time" required for this job, hhh:mm:ss
#PBS -l walltime=2:0:0
### Optional. cput = time x ncpus. If not included, default := cput = walltime x select x ncpus.
#PBS -l cput=1000:0:0
# --------------------------------------------------------------
### PART 2: Executes bash commands to run your job
# --------------------------------------------------------------
### Load required modules/libraries if needed
module load singularity/3.6.4
### Define path to singularity image that we will use for running commands
SING_IMG=/groups/claytonm/containers/pdf_eqn_miner_latest.sif
### Run commmands in the singularity container using exec.
### Command output will be sent to the appropriate output/error files generated by HPC.
### Created data that is saved in mounted locations (/groups is a safe bet) in the
### singularity container will be available on HPC after completing execution.
singularity exec $SING_IMG python3 
# singularity exec $SING_IMG pip3 list
# singularity exec $SING_IMG touch /groups/claytonm/test_out_file.txt
# singularity exec $SING_IMG pdflatex -version
