# !bin/bash



#PART 1: Requests resources to run your job.
# --------------------------------------------------------------
### Set the job name (needed for job lookup)
#PBS -N TB_1411-1412
### Specify the PI group for this job (always claytonm)
#PBS -W group_list=claytonm
### Set the queue for your job (options: windfall, standard, high_priority, debug -- only on Ocelote)
#PBS -q windfall
### Set the number of nodes, cores and memory that will be used for this job
### pcmem is optional as it defaults to 6gb per core. Note: mem=ncpus x pcmem
#PBS -l select=1:ncpus=28:mem=224gb:pcmem=8gb:np100s=1:os7=True
### Specify "wallclock time" required for this job, hhh:mm:ss
#PBS -l walltime=2:0:0
### Optional. cput = time x ncpus. If not included, default := cput = walltime x select x ncpus.
#PBS -l cput=56:0:0

#--------------------------------------------------------------
### PART 2: Executes bash commands to run your job
# --------------------------------------------------------------
### Load required modules/libraries if needed
### module load singularity/3.6.4
module load singularity/3/3.6.4
### Define path to singularity image that we will use for running commands
### SING_IMG=/groups/claytonm/containers/pdf_eqn_miner_latest.sif
### SING_IMG=/groups/claytonm/containers-other/pdf_eqn_miner_ubuntu18.sif
SING_IMG=/groups/claytonm/containers-other/pdf_eqn_miner_chardet_latest.sif

cd /home/u17/gauravs/TB

### Run commmands in the singularity container using exec.
### Command output will be sent to the appropriate output/error files generated by HPC.
### Created data that is saved in mounted locations (/groups is a safe bet) in the
### singularity container will be available on HPC after completing execution.
singularity exec $SING_IMG python3 TB.py -src '/xdisk/claytonm/projects/automates/er/gaurav/'  -yr 2014 -dir 1411 1412
# singularity exec $SING_IMG pip3 list
# singularity exec $SING_IMG touch /groups/claytonm/test_out_file.txt
# singularity exec $SING_IMG pdflatex -version
