version: "3"
services:
    scienceparse:
        image: allenai/scienceparse:2.0.3
        ports:
            - "8080:8080"
    grobidquantities:
        build: ./quantities
        image: clulab/quantities:latest
        ports:
            - "8060:8060"
