C File: test_module_02.f
C Purpose: Illustrates a Fortran module that defines values for several variables
C    that are used in the program that uses this module.
C
C Compile and run this program as follows:
C
C    gfortran -c test_module_02.f     # << this will create a file "mymod2.mod"
C    gfortran test_module_02.f        # << this will create a file "a.out"
C
C The output generated by this program is (see test_module_02-OUT.txt):
C
C   1234    2  3.1416 7753.469

!-------------------------------------------------------------------------------
      MODULE MYMOD2
      IMPLICIT NONE

      INTEGER :: X = 1234, Y = 2
      REAL :: PI = 3.1416
      END MODULE mymod2
!-------------------------------------------------------------------------------
      PROGRAM PGM
      USE mymod2      ! << case-insensitive

 10   FORMAT (I7, I5, F8.4)

      write (*,10) X, Y, PI

      stop
      end program PGM
!-------------------------------------------------------------------------------
