C File: test_module_10.f
C Purpose: This program shows how importing a module into a subprogram
C          (rather than the main program) limits visibility of the
C          imported variables to the subprogram and does not affect
C          variables in the main program.
C
C Compile and run this program as follows:
C
C    gfortran -c test_module_10.f     # << this will create a file "mymod10.mod"
C    gfortran test_module_10.f        # << this will create a file "a.out"
C
C The output generated by this program is (see test_module_10-OUT.txt):
C
C  123   234   345  1110  1110  1110
C  987   876   765  1110  1110  1110

!-------------------------------------------------------------------------------
      module mymod10
      implicit none
      integer :: x = 123, y = 234, z = 345
      end module mymod10

!-------------------------------------------------------------------------------
      subroutine f(u, v, w, a, b, c)
      use mymod10      ! << importing into a subprogram
      implicit none
      integer u, v, w, a, b, c

      a = u+x
      b = v+y
      c = w+z

 10   format(6(I5,X))
      write (*,10) x,y,z,a,b,c
      end subroutine f

!-------------------------------------------------------------------------------
      program main
      implicit none

      integer :: x, y, z, p, q, r  ! << Note that the variables x, y, z 
                                   !    are not affected by those in mymod10
      x = 987
      y = 876
      z = 765

      call f(x, y, z, p, q, r)

 10   format(6(I5,X))
      write (*,10) x,y,z,p,q,r

      stop
      end program main
!-------------------------------------------------------------------------------
