# coding: utf-8

"""
    GroMEt Metadata spec

    Grounded Model Exchange (GroMEt) Metadata schema specification  __Using Swagger to Generate Class Structure__  To automatically generate Python or Java models corresponding to this document, you can use [swagger-codegen](https://swagger.io/tools/swagger-codegen/). We can use this to generate client code based off of this spec that will also generate the class structure.  1. Install via the method described for your operating system    [here](https://github.com/swagger-api/swagger-codegen#Prerequisites).    Make sure to install a version after 3.0 that will support openapi 3. 2. Run swagger-codegen with the options in the example below.    The URL references where the yaml for this documentation is stored on    github. Make sure to replace CURRENT_VERSION with the correct version.    To generate Java classes rather, change the `-l python` to `-l java`.    Change the value to the `-o` option to the desired output location.    ```    swagger-codegen generate -l python -o ./client -i https://raw.githubusercontent.com/ml4ai/automates-v2/master/docs/source/gromet_metadata_v{CURRENT_VERSION}.yaml    ``` 3. Once it executes, the client code will be generated at your specified    location.    For python, the classes will be located in    `$OUTPUT_PATH/swagger_client/models/`.    For java, they will be located in    `$OUTPUT_PATH/src/main/java/io/swagger/client/model/`  If generating GroMEt Metadata schema data model classes in SKEMA (AutoMATES), then afer generating the above, follow the instructions here: ``` <automates>/automates/model_assembly/gromet/metadata/README.md ```   # noqa: E501

    OpenAPI spec version: 0.1.1
    Contact: claytonm@email.arizona.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TextExtraction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_reference_uid': 'str',
        'page': 'int',
        'block': 'int',
        'char_begin': 'int',
        'char_end': 'int'
    }

    attribute_map = {
        'document_reference_uid': 'document_reference_uid',
        'page': 'page',
        'block': 'block',
        'char_begin': 'char_begin',
        'char_end': 'char_end'
    }

    def __init__(self, document_reference_uid=None, page=None, block=None, char_begin=None, char_end=None):  # noqa: E501
        """TextExtraction - a model defined in Swagger"""  # noqa: E501
        self._document_reference_uid = None
        self._page = None
        self._block = None
        self._char_begin = None
        self._char_end = None
        self.discriminator = None
        if document_reference_uid is not None:
            self.document_reference_uid = document_reference_uid
        if page is not None:
            self.page = page
        if block is not None:
            self.block = block
        if char_begin is not None:
            self.char_begin = char_begin
        if char_end is not None:
            self.char_end = char_end

    @property
    def document_reference_uid(self):
        """Gets the document_reference_uid of this TextExtraction.  # noqa: E501

        uid of \\<document_reference>  # noqa: E501

        :return: The document_reference_uid of this TextExtraction.  # noqa: E501
        :rtype: str
        """
        return self._document_reference_uid

    @document_reference_uid.setter
    def document_reference_uid(self, document_reference_uid):
        """Sets the document_reference_uid of this TextExtraction.

        uid of \\<document_reference>  # noqa: E501

        :param document_reference_uid: The document_reference_uid of this TextExtraction.  # noqa: E501
        :type: str
        """

        self._document_reference_uid = document_reference_uid

    @property
    def page(self):
        """Gets the page of this TextExtraction.  # noqa: E501

        The COSMOS-assigned page number  # noqa: E501

        :return: The page of this TextExtraction.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this TextExtraction.

        The COSMOS-assigned page number  # noqa: E501

        :param page: The page of this TextExtraction.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def block(self):
        """Gets the block of this TextExtraction.  # noqa: E501

        The COSMOS-extracted text block from the page  # noqa: E501

        :return: The block of this TextExtraction.  # noqa: E501
        :rtype: int
        """
        return self._block

    @block.setter
    def block(self, block):
        """Sets the block of this TextExtraction.

        The COSMOS-extracted text block from the page  # noqa: E501

        :param block: The block of this TextExtraction.  # noqa: E501
        :type: int
        """

        self._block = block

    @property
    def char_begin(self):
        """Gets the char_begin of this TextExtraction.  # noqa: E501

        Character coordinate within a text block where span begins  # noqa: E501

        :return: The char_begin of this TextExtraction.  # noqa: E501
        :rtype: int
        """
        return self._char_begin

    @char_begin.setter
    def char_begin(self, char_begin):
        """Sets the char_begin of this TextExtraction.

        Character coordinate within a text block where span begins  # noqa: E501

        :param char_begin: The char_begin of this TextExtraction.  # noqa: E501
        :type: int
        """

        self._char_begin = char_begin

    @property
    def char_end(self):
        """Gets the char_end of this TextExtraction.  # noqa: E501

        Character coordinate within a text block where span ends  # noqa: E501

        :return: The char_end of this TextExtraction.  # noqa: E501
        :rtype: int
        """
        return self._char_end

    @char_end.setter
    def char_end(self, char_end):
        """Sets the char_end of this TextExtraction.

        Character coordinate within a text block where span ends  # noqa: E501

        :param char_end: The char_end of this TextExtraction.  # noqa: E501
        :type: int
        """

        self._char_end = char_end

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TextExtraction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TextExtraction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
