vars: org/clulab/aske_automates/grammars/vars.yml

rules:

  - name: value_entity
    label: Value
    priority: ${priority}
    type: token
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      [entity = /NUMBER|PERCENT|DURATION/ & tag = /CD/] (?! "/" @variable:Identifier)  (?! "of")

  - name: mult_value
    label: Value
    priority: ${priority}
    type: token
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      [entity = /NUMBER|PERCENT/ & tag = /CD/] [word = /x|-/] [entity = /NUMBER|PERCENT/ & tag = /CD/]
      |
      [entity = /NUMBER|PERCENT/ & !lemma = "%" & !tag=/TO|CC/]{2,}
      # note: second rule added to address cases like "12 milions". got rid of tag = /CD/ part ("millions" is captured as number, but does not have tag = /CD/. It is tagged as /NNS/.)

  - name: compound_value
    label: Value
    priority: ${compoundPriority}
    type: token
    example: "63 million of cats"
    pattern: |
      @Value ","? @Value



