from code_crawler import CodeCrawler

# Base packages
# import abc, aifc, argparse, array, ast, asynchat, asyncio, asyncore, atexit, audioop, base64, bdb, binascii, binhex, bisect, builtins, bz2, cProfile, calendar, cgi, cgitb, chunk, cmath, cmd, code, codecs, codeop, collections, colorsys, compileall, concurrent, configparser, contextlib, contextvars, copy, copyreg, crypt, csv, ctypes, curses, datetime, dbm, decimal, difflib, dis, distutils, doctest, dummy_threading, email, encodings, ensurepip, enum, errno, faulthandler, fcntl, filecmp, fileinput, fnmatch, formatter, fractions, ftplib, functools, gc, getopt, getpass, gettext, glob, grp, gzip, hashlib, heapq, hmac, html, http, imaplib, imghdr, imp, importlib, inspect, io, ipaddress, itertools, json, keyword, lib2to3, linecache, locale, logging, lzma, macpath, mailbox, mailcap, marshal, math, mimetypes, mmap, modulefinder, multiprocessing, netrc, nis, nntplib, numbers, operator, optparse, os, parser, pathlib, pdb, pickle, pickletools, pipes, pkgutil, platform, plistlib, poplib, posix, pprint, profile, pstats, pty, pwd, py_compile, pyclbr, pydoc, queue, quopri, random, re, readline, reprlib, resource, rlcompleter, runpy, sched, secrets, select, selectors, shelve, shlex, shutil, signal, site, smtpd, smtplib, sndhdr, socket, socketserver, sqlite3, ssl, stat, statistics, string, stringprep, struct, subprocess, sunau, symbol, symtable, sys, sysconfig, syslog, tabnanny, tarfile, telnetlib, tempfile, termios, test, textwrap, threading, time, timeit, tkinter, token, tokenize, trace, traceback, tracemalloc, tty, turtle, turtledemo, types, typing, unicodedata, unittest, urllib, uu, uuid, venv, warnings, wave, weakref, webbrowser, wsgiref, xdrlib, xml, xmlrpc, zipapp, zipfile, zipimport, zlib

# import absl, abstract_rendering, Acquisition, adal, aenum, affine, agate, agatedbf, agateexcel, agatesql, aiocontextvars, aiofiles, aiohttp, ajenti, alabaster, alembic, algorithms, alipay, altgraph, amqp, aniso8601, annoy, ansi, ansi2html, ansible, antiorm, anyjson, anykeystore, AnyQt, libcloud, apipkg, apistar, appdirs, appnope, appscript, apptools, apsw, argcomplete, argh, args, arrow, asciimatics, asgi_redis, asgiref, asn1crypto, astor, astroid, astropy, async_timeout, asyncio, atomicwrites, audiolazy, audioread, autobahn, autograd, automake, automat, automaton, autovizwidget, awkward, awscli, azure, babel, backcall, backpack, backports_abc, backports.functools_lru_cache, bandersnatch, bashplotlib, bcbio, bcolz, beaker, bs4, beets, bidict, billiard, binaryornot, Bio, bison, bitarray, bitstring, bleach, bleach_whitelist, blessings, blinker, blist, blockspring, blosc, bokeh, boltons, boost, boto, boto3, botocore, bottle, bottle_websocket, bottlechest, bottleneck, bpython, breadability, brewer2mpl, bsdiff4, BTrees, bz2file, cachecontrol, cached_property, cachetools, cactus, caffe2, carteblanche, cartridge, cassandra, cbor, cchardet, cclib, cement, cerberus, certifi, cffi, cfn_flip, cftime, chainer, chalmers, chameleon, characteristic, chardet, check_manifest, cheroot, cherrypy, chest, chronyk, circleci, cleo, cli_helpers, click, click_completion, click_default_group, click_didyoumean, click_plugins, cliff, cligj, clint, clinto, closure, cloudpickle, clyent, cmake, cmarkgfm, cmd2, cmigemo, coconut, cocos, codecov, colander, colorama, colorcet, colorclass, colorlog, colosseum, colour, commando, conda, config, configargparse, configobj, configparser, constantly, contextlib2, contextvars, cookiecutter, cookies, coreapi, coreapi_cli, coreschema, cornice, coverage, cram, croniter, crossbar, cryptacular, cryptography, cssselect, cssselect2, cssutils, csvkit, cubes, curdling, curtsies, cvxopt, cvxpy, cx_Oracle, cycler, cymem, cyordereddict, cypari, cython, cytoolz

# import daemonize, daiquiri, daphne, dash, dash_renderer, dask, datashape, dateparser, datetime, datrie, dbf, dbfread, debtcollector, decorator, deform, defusedxml, delegator, delorean, demiurge, dependency_management, descartes, devpi, dialite, dill, diskcache, distlib, dj_database_url, djedi, docker, dockerpty, docopt, docutils, docx2txt, dodgy, dogpile.cache, doit, doitlive, dotted, doublex, draftjs_exporter, dulwich, durationpy, dynaconf, dynamo3, dynet, easy_thumbnails, ebooklib, ecdsa, ecos, eel, elasticsearch, eliot, elpy, enaml, entrypoints, envelopes, envisage, ephem, errbot, esengine, et_xmlfile, eve, eventlet, events, execnet, exifread, expressions, eyed3, fabric, facebook, facepy, factory, fake_useragent, fake2db, faker, fakeredis, falcon, fanstatic, fast_histogram, fastcache, fasteners, fastFM, faust, feedgenerator, feedparser, feincms, filebrowser_safe, filelock, fiona, fisher, fitparse, flake8, flanker, flask, flask_admin, flask_api, flask_assets, flask_babelex, flask_compress, flask_cors, flask_httpauth, flask_login, flask_oauthlib, flask_restful, flask_restless, flask_simplelogin, flask_sqlalchemy, flask_wtf, flex, flexx, flower, flywheel, fn, forex_python, formencode, freezegun, flask_frozen, fswrap, ftfy, fuckit, fuel, funcy, furl, future, futurist, fuzzyfinder, fuzzywuzzy, gast, genshi, genson, geographiclib, geojson, geopy, geos, gevent, gffutils, ggplot, github_release, glmnet_py, glob2, glog, glue, gmail, gooey, googleapiclient, google_auth_httplib2, grab, grako, graphviz, grappelli_safe, green, greenlet, grequests, gridmap, grpc, gsl, gspread, gunicorn, gym

# import h2, h2o, h5py, happybase, hashids, hdijupyterutils, hdmedians, headers_workaround, heapdict, hermes, hexdump, hiredis, hjson, holoviews, honcho, hopcroftkarp, hot_redis, howdoi, hpack, html2text, html5lib, htmlfetcher, htmlparsing, httmock, http_ece, httpie, httplib2, httpretty, httptools, huey, hug, humanize, hunter, hupper, hurry, hyde, hyperframe, hyperlink, hypothesis, icecream, idna, idna_ssl, imageio, imagesize, imbox, iminuit, immutables, implicit, import_string, importlib_metadata, importmagic, impala, inbox, incremental, infinity, inflection, inifile, ino, intervals, intervaltree, into, invoke, ipaddress, ipdb, IPy, ipykernel, ipyparallel, IPython, ipywidgets, iso8601, isodate, isort, itsdangerous, itypes, jaraco, javabridge, jdcal, jedi, jellyfish, jieba, jinja2, jinja2_time, jmespath, joblib, johnny, js, jsmin, json_tricks, jsonpickle, jsonpointer, jsonschema, jnpr, jupyter, jupyter_client, jupyter_console, jupyter_core, jupyterlab, jupyterlab_server, jwcrypto, kafka, kappa, kaptan, keras, keras_applications, keras_preprocessing, keyboard, kiwisolver, kmapper, kombu, kotti, kubernetes

# import lambda_packages, lamson, langid, lassie, lazy_object_proxy, ldap3, leather, lektor, leveldb, libthumbor, libtmux, lepl, kivy, line_profiler, linecache2, lingua, livereload, llvmlite, lmdb, lml, localshop, locket, lockfile, log_colorizer, logbook, logilab, lru, luigi, lxml, lz4

# import m3u8, macholib, magicdate, mako, mamba, manage, manhole, markdown, markdown2, markupsafe, marrow, marshmallow, martian, mastodon, matplotlib, maya, mayavi, mccabe, mdp, mechanicalsoup, meinheld, meld3, memory_profiler, meshio, meta, metrics, mezzanine, micawber, mimeparse, mimerender, mimesis, mingus, mistune, mixer, mizani, mkdocs, mock, mocket, mode, model_mommy, modernize, modoboa, modulegraph, moment, money, mongoengine, monkeytype, monotonic, monty, more_itertools, motor, moviepy, mpc, mpi4py, mpl_scatter_density, mpld3, mpmath, mrjob, mrq, msgpack, msgpack_numpy, msgpack, msrest, msrestazure, mtq, multidict, multimethods, multipledispatch, multiprocess, munch, munkres, murmurhash, musicbrainzngs, mutagen, mxnet, mycli, mypy, mypy_extensions, mysql, nameparser, nano, napalm, natsort, nbconvert, nbformat, ncclient, ndg, ndicapy, neo4j, neon, neotime, netaddr, netCDF4, netifaces, netius, netmiko, networkx, neupy, nibabel, nikola, ninja, nipy, nltk, nodejs, nose, nose_parameterized, nose2, nosexcover, notebook, npstreams, nuitka, numba, numexpr, numpy, numpydoc, oauth2client, oauthlib, objgraph, obspy, odf, odo, olefile, openpyxl, opps, optimus, optional_django, Orange, orderedmultidict, oslo_i18n, oslo_serialization, oslo_utils, otree

# import p, pa, packaging, pagan, palettable, panda3d, pandas, pandas_datareader, pandas_profiling, pandasql, pandocfilters, pangu, param, paramiko, parse, parsedatetime, parsel, parso, partd, passlib, paste, paste, pastel, path, pathlib2, pathspec, pathtools, patsy, pbkdf2, pbr, pdoc, peewee, pefile, pelican, pendulum, pep8, peppercorn, percol, persim, persistent, petl, petlx, pexpect, pgcli, pgspecial, phonenumbers, picklable_itertools, pickledb, pickleshare, piexif, PIL, pip, pipdate, pivottablejs, pkgconfig, pkginfo, plac, placebo, plan, plaster, plaster_pastedeploy, plink, plotly, plotnine, pluggy, ply, polib, polyglot, pomegranate, portend, portpicker, posix_ipc, pox, poyo, preshed, prettytable, priority, profig, profiling, progressbar, progressbar, prometheus_client, prompt_toolkit, prospector, pscript, psutil, psycopg2, ptpython, ptyprocess, pudb, pulp, pulsar, purl, py, bcrypt, cpuinfo, dateutil, ubjson, py2app, py2neo, py4j, pyamg, pyaml, pyasn1, pyasn1_modules, pyAudioAnalysis, pyautogui, barcode, pybedtools, pybind11, pybuilder, pycallgraph, pycco, pychievements, CifFile, pycodestyle, pycosat, pycparser, Crypto, pyct, pydal, pydispatch, pydocstyle, pydot, pydot_ng, pydotplus, pydub, pydy, pyeapi, pyechonest, pyee, elftools, pyexcel, pyexcel_io, pyface, pyfaidx, pyfiglet, pyflakes, pygal, pygame, pygeoip, pyglet, pygments, pygments_markdown_lexer, pygram, pygraphviz, hamcrest, pyIOSXR, jwt, kerberos, pykit, pylama, pylev, pylint, pylint_celery, pylint_django, pylint_plugin_utils, pymatgen, pymc3, pymongo, pymsgbox, pymysql, nacl, pynamodb, nsist, pynxos, objc, pyocr, OpenGL, OpenSSL, pypandoc, pyparsing, pypattyrn, PyPDF2, pypdt, pyperclip, pyphen, png, pyppeteer, pyprint, pyprof2calltree, pyproj, pyqrcode, PyQt5, pyqtgraph, pyquery, pyramid, pyramid_beaker, pyramid_chameleon, pyramid_debugtoolbar, pyramid_deform, pyramid_jinja2, pyramid_mailer, pyramid_mako, pyramid_tm, pyramid_zcml, pyrect, pyrsistent, PyRSS2Gen, pysal, pysam, pyscreeze, serial, pyshorteners, PySide2, PySimpleGUI, pysmi, pysnmp, socks, pysolr, pyspark, pystache, pystan, pystorm, pyte, pytesseract, pytest, pyth, box, catcher, coveralls, daemon, decouple, docx, dotenv, editor, exconsole, fire, gettext, gflags, gitlab, jwt, ldap, Levenshtein, magic, mimeparse, modargs, ntlm, oauth2, oembed, patterns, pptx, rapidjson, redis_lock, slugify, snappy, sql, utils, openid, pytils, pytime, pytimeparse, pytools, torchnlp, pytrie, pytweening, pytz, pytzdata, pymouse, pykeyboard, pyutilib, pyviz_comms, pywt, yaml, zmq

# import qgrid, qrcode, qtawesome, qtconsole, qtpy, quandl, queries, queuelib, quokka, qutip, radar, rapidjson, rasterio, rauth, raven, rcssmin, readability, readline, readme_renderer, reconfigure, redis, redisco, regex, relatorio, remote_pdb, reportlab, repoze.lru, repoze.sendmail, repoze.workflow, repoze.zcml, requests, requests_cache, requests_download, requests_file, requests_ftp, requests_html, requests_kerberos, requests_oauthlib, requirements_detector, responses, restless, retrying, retype, rfc3987, rfc6266, rfc6266_parser, ripozo, ripser, rjsmin, aiokafka, robobrowser, rocket, rope, routes, rq, rsa, ruamel, rubicon, runipy, s3fs, s3transfer, s4cmd, sacred, sanction, sanic, sarge, sas7bdat, saws, scandir, scapy, schedule, schema, schematics, skaero, allel, skbio, skblocks, skbuild, skchainer, ci, ci_addons, skcmeans, skcriteria, skctr, skcycling, skdata, skdatasets, scikit_ext, skfem, skfmm, skfusion, skfuzzy, skgarden, geodesic, skgof, skgraph, skgrni, skgroups, skgstat, skgym, skhep, skimage, skintervals, skkda, skkeras, skinematics, sklearn, skluc, mdr, skmetrics, skmisc, skmonaco, skmultiflow, skmultilearn, sknano, sknetwork, sknn, skopt, skotree, scikitplot, scikit_posthocs, skprocrustes, skqfit, skreflectometry, skrf, scikit_ribo, sksacred, scikit_small_ensemble, sksos, sksound, skspark, skstack, sksurgery, sksurgerycore, sksurgeryimage, sksurgerynditracker, sksurgeryoverlay, sksurgeryvideoutils, sksurgeryvtk, surprise, sksurv, sktda, traveltime, skued, scikits.umfpack, skvalidate, skvideo, skvis, skvisualizations, scipy, scons, scoop, scp, scrapy, sdnotify, seaborn, see, selection, selectors2, selenium, semantic_version, semver, send2trash, serpent, serverfiles, service_identity, setoptconf, setproctitle, setuptools, setuptools_scm, sh, shapely, shellingham, shiboken2, short_url, shortuuid, shutilwhich, simplegeneric, simplejson, simpy, singledispatch, sip, six, sixpack, smartypants, smmap, snakebite, snakeviz, snappy, snappy_manifolds, snaptime, snowballstemmer, snownlp, snuggs, sockjs, solr, sorl, sortedcollections, sortedcontainers, soupsieve, south, spacy, spark_parser, sparkmagic, speaklater, speech_recognition, spglib, spherogram, sphinx, sphinx_me, sphinx_rtd_theme, splinter, sputnik, spyder, spyder_kernels, sqlalchemy, sqlalchemy_utils, sqlparse, statsd, statsmodels, stevedore, stream_framework, streamparse, strict_rfc3339, strictyaml, stripe, subprocess32, suds, sumy, surprise, svn, sympy

# import tableprint, tables, tablib, tabpy_client, tabpy_server, tabulate, tadasets, tailer, tangent, taskflow, tblib, telephus, tempita, tempora, tenacity, tensorboard, tensorflow, tensorrec, teradata, termcolor, terminado, terminaltables, termstyle, testpath, text_unidecode, textblob, textdistance, textfsm, texttable, theano, thefuck, thinc, thrift, thriftpy, tifffile, times, tinkerer, tinycss2, tinydb, tinydb_serialization, tinymongo, tinytag, tld, tmuxp, toapi, toga, toml, tomorrow, toolz, torch, torchtext, torchvision, tornado, tornado_json, toro, tox, tqdm, traceback2, trading_calendars, traitlets, traits, traitsui, traittypes, transaction, translationstring, treq, trollius, troposphere, twisted, twython, txaio, txpostgres, txzmq, typed_ast, typing_extensions, typogrify, tzlocal, umsgpack, ua_parser, ujson, umap, uncompyle6, unicodecsv, unidecode, unidiff, unipath, unittest2, unp, untangle, uproot, uproot_methods, uritemplate, urllib3, urwid, user_agent, user_agents, uuid, uvloop, validate_email, validators, valideer, valuedispatch, vcversioner, velruse, venusian, versio, vibora, vincent, vine, virtualenv, virtualenvwrapper, vispy, visvis, voluptuous, vprof, vtk, w3lib, wagtail, waitress, wand, watchdog, wcwidth, wdb, webargs, webassets, webencodings, weblib, webob, webruntime, websocket, websockets, webtest, werkzeug, wget, wheel, whichcraft, whitenoise, whoosh, widgetsnbextension, wifi, willow, winpython, wooey, word2vec, workerpool, wrapt, ws4py, requestlogger, wtforms, wtfrecaptcha, wurlitzer, wx, xarray, xdis, xgboost, xhtml2pdf, xlrd, xlsxwriter, xlutils, xlwings, xlwt, xmldataset, xmlrpc2, xmltodict, xpinyin, xray, yapsy, yarg, yarl, you_get, youtube_dl, yt, yuicompressor, z3c, zappa, zc, ZConfig, zdaemon, ZEO, zerorpc, zExceptions, zict, zipp, ZODB, zodbpickle, zope, cv2, depot, fsevents, openTSNE, socketio, websocket, pasta


def main():
    modules = []
    ccrawler = CodeCrawler(modules=modules)
    print("Building function dict")
    ccrawler.build_function_dict()
    print("Building code/comment dict")
    ccrawler.build_code_comment_pairs()
    print("Getting output sentences")
    ccrawler.get_sentence_output()
    print("Outputting clean comments")
    ccrawler.output_clean_comments()
    print("done.")


if __name__ == '__main__':
    main()
