name: AutoMATES documentation deployment

on:
  push:
    branches: 
      - master

jobs:
  deploy_docs:
    runs-on: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2

    - name: Build docs with Sphinx
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install \
          git \
          curl \
          build-essential \
          gcc \
          pkg-config \
          python3 \
          python3-dev \
          python3-pip
        pip3 install --upgrade setuptools
        pip3 install wheel
        pip3 install -r requirements.txt
        cd docs
        mkdir -p build
        pushd docs > /dev/null
          make apidocs
          make html
        popd > /dev/null
    - name: Deploy docs to ml4ai.github.io/automates
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs/_build/html