# Workflow for continuous integration and testing

name: Continuous Integration

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  continuous_integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          CI_ENV=`bash <(curl -s https://codecov.io/env)`
          TR_IMAGE=ml4ailab/automates:tr-pipeline
          ASSEMBLY_IMAGE=ml4ailab/automates:assembly-pipeline
          sudo apt-get -y --no-install-recommends install wget
          docker pull $TR_IMAGE
          wget http://vanga.sista.arizona.edu/automates_data/vectors.txt -O $GITHUB_WORKSPACE/automates/text_reading/src/test/resources/vectors.txt
          docker run -itd --rm -v $GITHUB_WORKSPACE:/automates --name test-con $TR_IMAGE
          docker exec -w /automates/automates/text_reading test-con sbt -Dapps.projectDir=/automates test
          docker stop test-con
          docker image rm -f $TR_IMAGE
          docker pull $ASSEMBLY_IMAGE
          docker run $CI_ENV -itd --rm -v $GITHUB_WORKSPACE:/automates --name test-con $ASSEMBLY_IMAGE
          docker exec test-con pip install -e .
          docker exec test-con make test
          docker exec -e CODECOV_TOKEN=$CODECOV_TOKEN test-con bash -c 'bash <(curl -s https://codecov.io/bash)'
