# Workflow for continuous integration and testing

name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ml4ai/automates'
    strategy:
      matrix:
        os: [ubuntu-20.04]


    steps:
    - uses: actions/checkout@v2

    - name: Continuous Integration
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends apt-utils\
            git curl gcc build-essential \
            pkg-config openjdk-8-jdk antlr4 \
            python3 python3-dev python3-pip \
            graphviz libgraphviz-dev doxygen
        pip3 install --upgrade setuptools
        pip3 install wheel
        pip3 install -e .
        make test