# Workflow for continuous integration and testing

name: Continuous Integration

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  continuous_integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          CI_ENV=`bash <(curl -s https://codecov.io/env)`
          IMAGE=ml4ailab/automates:latest
          docker pull $IMAGE
          docker run $CI_ENV -itd --rm -v $GITHUB_WORKSPACE:/automates --name build-con $IMAGE
          docker exec build-con make test
          docker exec -e CODECOV_TOKEN=$CODECOV_TOKEN build-con bash -c 'bash <(curl -s https://codecov.io/bash)'
