# Workflow for continuous integration and testing

name: Continuous Integration

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  continuous_integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ml4ailab
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
          image_name: ml4ailab/automates
          image_tag: latest
      - name: Run unit tests
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          CI_ENV=`bash <(curl -s https://codecov.io/env)`
          docker run $CI_ENV -itd --rm -v $GITHUB_WORKSPACE:/automates --name build-con $FULL_IMAGE_NAME
          docker exec build-con make test
          docker exec -e CODECOV_TOKEN=$CODECOV_TOKEN build-con bash -c 'bash <(curl -s https://codecov.io/bash)'
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     files: ./coverage.xml
      #     flags: unittests
      #     env_vars: Python,Scala
      #     name: codecov-umbrella
      #     # TODO: add CI failure back in once demo season ends
      #     # fail_ci_if_error: true
      #     verbose: true
